// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCprTwBuPOw_7HPCH9LTIqjr0giPWZpSJ4',
    appId: '1:1054978058064:web:52d82df8e092c989072e55',
    messagingSenderId: '1054978058064',
    projectId: 'doan-91a74',
    authDomain: 'doan-91a74.firebaseapp.com',
    storageBucket: 'doan-91a74.appspot.com',
    measurementId: 'G-200BNXZWTM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPL8PSsplPouuEuzMYqFnFFOGMy1A5b4',
    appId: '1:1054978058064:android:15babfbceebbe0b7072e55',
    messagingSenderId: '1054978058064',
    projectId: 'doan-91a74',
    storageBucket: 'doan-91a74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXNnSGKQpgdRICumX2AahNQXhbNphaLX4',
    appId: '1:1054978058064:ios:5bf5c5e6807f8e7d072e55',
    messagingSenderId: '1054978058064',
    projectId: 'doan-91a74',
    storageBucket: 'doan-91a74.appspot.com',
    iosBundleId: 'com.example.doanTn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXNnSGKQpgdRICumX2AahNQXhbNphaLX4',
    appId: '1:1054978058064:ios:5bf5c5e6807f8e7d072e55',
    messagingSenderId: '1054978058064',
    projectId: 'doan-91a74',
    storageBucket: 'doan-91a74.appspot.com',
    iosBundleId: 'com.example.doanTn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCprTwBuPOw_7HPCH9LTIqjr0giPWZpSJ4',
    appId: '1:1054978058064:web:59b10f8b9b8e758b072e55',
    messagingSenderId: '1054978058064',
    projectId: 'doan-91a74',
    authDomain: 'doan-91a74.firebaseapp.com',
    storageBucket: 'doan-91a74.appspot.com',
    measurementId: 'G-CMT0D9CFGB',
  );
}
